version: '3'

services:
  action-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: rasa/rasa-sdk:3.5.0
    volumes:
      - './actions:/app/actions'
    ports:
      - '5055:5055'
    command: 'rasa run actions --actions actions'
  rasa-server:
    image: rasa/rasa:3.5.1-full
    volumes:
      - '.:/app'
    ports:
      - '5005:5005'
    command: 'run -m models --enable-api --cors "*"' 


    
